# Core Colors
background            #15130b
foreground            #e8e2d4
selection_foreground  #dac76f
selection_background  #393000
cursor                #dac76f
cursor_text_color     #15130b

# Regular Colors
color0  #15130b
color1  #ffb4ab
color2  #dac76f
color3  #a9d0b4
color4  #f7e388
color5  #ede2bc
color6  #d1c6a2
color7  #e8e2d4

# Bright Colors
color8  #3c3930
color9  #ffb4ab
color10 #dac76f
color11 #a9d0b4
color12 #f7e388
color13 #ede2bc 
color14 #d1c6a2
color15 #e8e2d4
