# Core Colors
background            #181115
foreground            #eddfe4
selection_foreground  #f8b1dc
selection_background  #501e41
cursor                #f8b1dc
cursor_text_color     #181115

# Regular Colors
color0  #181115
color1  #ffb4ab
color2  #f8b1dc
color3  #f4ba9f
color4  #ffd8ed
color5  #fbd9eb
color6  #debece
color7  #eddfe4

# Bright Colors
color8  #3f373b
color9  #ffb4ab
color10 #f8b1dc
color11 #f4ba9f
color12 #ffd8ed
color13 #fbd9eb 
color14 #debece
color15 #eddfe4
