name = "wallpapers"
name_pretty = "Wallpapers"
icon = "preferences-desktop-wallpaper"

[[entries]]
text = "macbookstyle.jpeg"
icon = "/home/thui/dotfiles/wallpapers/macbookstyle.jpeg"
actions = { "apply" = "/home/thui/dotfiles/hypr/scripts/wallpaper/set-wallpaper.sh /home/thui/dotfiles/wallpapers/macbookstyle.jpeg" }

[[entries]]
text = "_.jpeg"
icon = "/home/thui/dotfiles/wallpapers/_.jpeg"
actions = { "apply" = "/home/thui/dotfiles/hypr/scripts/wallpaper/set-wallpaper.sh /home/thui/dotfiles/wallpapers/_.jpeg" }
