$hyprlockDir = $HOME/dotfiles/hyprlock

source = $hyprlockDir/colors.conf

$battery  = $hyprlockDir/scripts/battery.sh
$location = $hyprlockDir/scripts/location.sh
$weather  = $hyprlockDir/scripts/weather.sh

source = $hyprlockDir/layouts/layout16.conf
