[General]
Background=background.jpeg
Avatar=avatar.jpeg
Font=Adwaita Sans
FallbackUser=thui

# Keep these values paired with hyprlock/layouts/layout16.conf.
DateTopMargin=125
TimeTopMargin=145
AvatarBottomMargin=185
UserBottomMargin=125
PasswordBottomMargin=65
