$cover = /tmp/hyde-mpris.png
$wall = $hyprlockDir/wallpapers/16.jpeg

general {
    immediate_render = true
    no_fade_in = true
    no_fade_out = true
    disable_loading_bar = false
    hide_cursor = false
    transparent = true
}

# BACKGROUND
background {
    path = $wall
    blur_passes = 0
}

# Time - Hours
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +"%I")</span>"
    color = rgb(240, 231, 219)
    font_size = 60
    font_family = JetBrains Mono
    position = -60, 400
    halign = center
    valign = center
}

# Time - Minutes
label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +":%M")</span>"
    color = rgb(214, 209, 209)
    font_size = 60
    font_family = JetBrains Mono
    position = 45, 400
    halign = center
    valign = center
}

# Day-Month-Date
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%A, %B %d")"
    color = rgb(200, 200, 200)
    font_size = 19
    font_family = JetBrains Mono
    position = 0, 340
    halign = center
    valign = center
}

# Profile Photo
image {
    monitor =
    path = $hyprlockDir/wallpapers/me.jpeg
    border_size = 2
    size = 190
    rounding = -1
    rotate = 0
    reload_time = -1
    position = 0, 0
    halign = center
    valign = center
}

# USER-BOX
shape {
    monitor =
    size = 200, 50
    color = rgb(0, 0, 0)
    rounding = 15
    border_size = 0
    rotate = 0
    xray = false
    position = 0, -310
    halign = center
    valign = center
}

# USER greeting
label {
    monitor =
    text = thui
    color = rgba(216, 222, 233, 0.80)
    font_size = 13
    position = 0, -310
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 200, 50
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0)
    inner_color = rgb(0, 0, 0)
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    placeholder_text = <i><span foreground="##ffffff99">  Enter password</span></i>
    hide_input = false
    position = 0, -375
    halign = center
    valign = center
    rounding = 15
}

# Weather div
shape {
    monitor =
    size = 240, 80
    color = rgba(30, 30, 30, 0.85)
    rounding = 20
    rotate = 0
    position = 810, -60
    halign = center
    valign = top
    zindex = 1
}

# Weather + Location
label {
    monitor =
    text = cmd[update:60000] echo -e "$($weather)\n$($location)"
    color = rgb(240, 231, 219)
    font_size = 12
    font_family = JetBrainsMono Nerd Font Mono
    text_align = center
    position = 810, -80
    halign = center
    valign = top
    zindex = 5
}
