-- Generated by Matugen. Do not edit the generated hypr/theme.lua directly.
return {
	primary = "{{colors.primary_fixed_dim.default.hex}}",
	outline = "{{colors.outline.default.hex}}",
	outline_variant = "{{colors.outline_variant.default.hex}}",
	shadow = "{{colors.shadow.default.hex}}",
}
